apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: platform-root
  namespace: redhat-astronaut
spec:
  exceptions:
    - policyName: require-secure-deployments
      ruleNames:
        - disallow-root-user
  match:
    any:
      - resources:
          kinds:
            - Pod
            - Deployment
          namespaces:
            - redhat-astronaut
